USE GEEMSDB;

ALTER TABLE Pago
ALTER COLUMN MontoBruto DECIMAL(18,3) NOT NULL;

ALTER TABLE Pago
ALTER COLUMN MontoPago DECIMAL(18,3) NOT NULL;


ALTER TABLE Deducciones
ALTER COLUMN Monto DECIMAL(18,3) NOT NULL;


ALTER TABLE Deducciones
ADD Nombre NVARCHAR(100) NULL;