USE GEEMSDB;

ALTER TABLE Persona
ADD EstaBorrado BIT NOT NULL DEFAULT 0;

ALTER TABLE Usuario
ADD EstaBorrado BIT NOT NULL DEFAULT 0;

ALTER TABLE Empleado
ADD EstaBorrado BIT NOT NULL DEFAULT 0;

ALTER TABLE Empresa
ADD EstaBorrado BIT NOT NULL DEFAULT 0;